### ISSUE TITLE
Add styling for contact cards

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-app#3010]
**Is your feature request related to a problem? Please describe.**
Once digitalfabrik/integreat-cms#3169 is merged, regions will be able to insert contact cards into pages. While the CMS/api will provide the HTML markup for the card ready-to-use, due to [the reasons discussed here](https://chat.tuerantuer.org/digitalfabrik/pl/qpewk4im8bf3f8uqwcgmpi3w1c) and [here](https://chat.tuerantuer.org/digitalfabrik/pl/arfrdebp6bnr9xd1acx76xhw3y), styling should be handled by the app.

Feel free to either copy the styling from the CMS (kudos @PeterNerlich):
![image](https://github.com/user-attachments/assets/b1ca6679-a228-4569-b3a6-d9a6fa444912)

```css
.contact-card {
    display: inline-block;
    box-sizing: border-box;
    padding: 1rem;
    border-radius: 0.25rem;
    background-repeat: no-repeat;
    background-color: rgba(127, 127, 127, 0.15) !important;
    background-image: linear-gradient(to right, rgba(255, 255, 255, 0.9) 0 100%), url("../svg/contact.svg") !important;
    background-blend-mode: difference;
    background-position: calc(100% + 2em) calc(100% + 1em);
    background-size: 7em;
    box-shadow: 0 0.1em 0.1em rgba(0, 0, 0, 0.4);
    cursor: default !important;
    color: initial;
    text-decoration: initial;
    min-width: 50%;
    white-space: initial !important;

    p {
        margin: 4px 0 0 0;
    }

    h4 {
        margin: 0 0 12px 0;
    }
}
``` 
or to come up with your own web/app specific styling 😄 

**Describe the solution you'd like**
Add styling for the `contact-card` class on web and mobile.

**Describe alternatives you've considered**
None. Styling in the CMS comes with some hurdles we'd rather avoid.

**Additional context**
CMS issue: https://github.com/digitalfabrik/integreat-cms/issues/2959
~~Each `.contact-card` will contain a `.marker-link` which should receive `display: none` as its styling.~~ This one is done inline.
